name: 🔨 Build Test
on:
  push:
  pull_request:
  workflow_dispatch:


jobs:  
  build:
    name: Test Builds
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...

      - name: Build and Run
        run: go run .
        working-directory: cmd/example
